Error: Cannot find control with path: 'rows -> 1 ->
- initialize createRow fun with Interface ,
- use createRow fun for populating form as well creating new row
- static data is used here, array of JSON